### ISSUE TITLE
List: Show all

### ISSUE THREAD

**Issue by JulianKunkel** [VI4IO/io-500-webpage#11]
I find it very cumbersome to scroll the pages, can we make it so that by default it shows all list entries as it was?
https://www.jbez.io500.org/site/releases/historical/isc19

**Comment by johnbent** [comment]
Good point.  Jean Luca, could you please add a 'Single Page View' link next to the pagination interface?  In the 'Single Page View' can you have a link for 'Return to Paginated View' please?  And please save that preference so that the user doesn't need to redo their preference for every list?

**Comment by johnbent** [comment]
And, please follow Julian's request that the default be 'Single Page View' and not include the option for pagination unless the number of entries is greater than 100?  And maybe if the number of entries is greater than 500, the default should be pagination?  And we can adjust these values as we observe problematic latency in rendering lists with large numbers of entries.  And please add as values in the config file to make this easy to change.  Thanks!

**Comment by jeanbez** [comment]
I've included a parameter that sets the default number of entries that should be displayed in each list. In the cases it does not require pagination, it will no be displayed. 

My only concern is with the full and historical lists that should grow much faster than the other ones. If the default view is a 'single page view' we could observe some overhead to load and render the page as the number of records increase. For now it would be better just to set this parameter to a higher value such as 100 or 500 to accommodate all the entries in a single page and once we see that starts to get slow we can then set the 'paginated view' as default for these two list types. Does this sounds ok?
