### ISSUE TITLE
Browse files very slow

### ISSUE THREAD

**Issue by JulianKunkel** [VI4IO/io-500-webpage#13]
Clicking on browse files takes a long time to startup (10s for me first time). It is generally nice but maybe we should reconsider the concept. As the number of files growth over time, it may become slower over time.
https://jbez.io500.org/storage/isc19/2019-06-09-UniversityofCambridgeLustre-512-16

**Comment by johnbent** [comment]
Good catch.  This can be massively sped up by jumping to only the specific folder for a submission as opposed to going to the folder that holds all submissions.  Jean Luca, can you make this change please?

**Comment by jeanbez** [comment]
I make some changes on the configuration of the server. @JulianKunkel could you please try accessing it again? Is is better now?

**Comment by johnbent** [comment]
Closing this as it seems to work pretty well now.  Please re-open if you are still having issues.
