### ISSUE TITLE
Changed structure of the page

### ISSUE THREAD

**Issue by JulianKunkel** [VI4IO/io-500-webpage#15]
We had about => steering as subpage.
Now steering is top-level. Should we create subpages in the navigation as it was?

**Comment by johnbent** [comment]
We can definitely nest 'Steering' into a pull-down list under 'About'.  But that's a bit weird perhaps to have a pull-down list with only 'one' item in it.  So three options:
1. Move 'Steering' out of the top nav bar and make it just be a link inside 'About' page.
2. Make a pull-down for 'About' which includes 'About' and 'Steering'
3. Leave 'Steering' in the top nav bar.

Jean Luca, all are equivalently easy to do.  Julian, do you have a preference in these three options or other options?

**Comment by johnbent** [comment]
Didn't hear anything about this for 28 days.  Assuming current approach is fine.  Please re-open if otherwise.
