### ISSUE TITLE
Unify Formating of news

### ISSUE THREAD

**Issue by JulianKunkel** [VI4IO/io-500-webpage#16]
We had one case in which two subnews for a given news was created:
"Congrats to ORNL for their Summit machine which took over the #1 overall spot and also won the “10 Node Challenge”.
"A total of 54 new submissions from 19 different institutions!"
on https://www.jbez.io500.org/site/news

I found the past sublist clearer. We should think about what requirements we have for news and then organize it accordingly.

**Comment by johnbent** [comment]
Jean Luca, can you change this one please to make those two entries by sub-bullets?
