### ISSUE TITLE
Name broken

### ISSUE THREAD

**Issue by JulianKunkel** [VI4IO/io-500-webpage#17]
https://www.jbez.io500.org/site/releases/view/24
State Key Laboratory of High-end Server & Storage Technologyï¼ˆHSSï¼‰

**Comment by johnbent** [comment]
@jeanbez can you fix this one please?

**Comment by jeanbez** [comment]
Yes, fixed directly in the database encoding for this record.

**Comment by adilger** [comment]
I verified that this was fixed.
