### ISSUE TITLE
Graphs do not work

### ISSUE THREAD

**Issue by gmarkomanolis** [VI4IO/io-500-webpage#26]
Hi, the graphs menu doesn't visualize something

https://johnbent.io500.org/releases/mdtest

**Comment by adilger** [comment]
I'm using http://www.jbez.io500.org/site/releases/ior without a problem.  The only minor issue is that the mouseover never shows the filesystem type:

<img width="1074" alt="Screen Shot 2020-07-19 at 14 38 34" src="https://user-images.githubusercontent.com/167584/87884722-a57af980-c9cd-11ea-8eb4-a5cc8a7a512c.png">

Maybe "Filesystem:" is supposed to show the name, but it is never filled in?  IMHO, showing the type would be more useful.

**Comment by gmarkomanolis** [comment]
That moment that I tried, it was not loading, now it loads.

**Comment by gmarkomanolis** [comment]
It is happening again now. 

<img width="1195" alt="Screen Shot 2020-07-19 at 8 41 27 PM" src="https://user-images.githubusercontent.com/2506875/87889613-7631b000-ca00-11ea-9c40-8a169ec40271.png">

**Comment by adilger** [comment]
I tried it again, and the graphs worked for me...

George, maybe you just had a temporary connection issue?

**Comment by gmarkomanolis** [comment]
It was for around 24 hours with different connections, it was working on another domain that John provided

**Comment by johnbent** [comment]
Closing.  Please re-open if you are still having problems.
