### ISSUE TITLE
Temporarily Disable Saving Derived Views

### ISSUE THREAD

**Issue by johnbent** [VI4IO/io-500-webpage#3]
@jeanbez can you please temporarily disable the feature that saves derived views and allows them to be listed and allows them to have comments on them?  We need to agree on language on those pages to make it clear that these derived lists are not official IO500 lists but are merely community derived interpretations of the official lists.  Subsequently we can use this issue to start drafting that text.

**Comment by jeanbez** [comment]
@johnbent Sure! I included an option in the code to quickly turn this feature on/off if required.
