### ISSUE TITLE
Comments on differently sorted views of the same list

### ISSUE THREAD

**Issue by johnbent** [VI4IO/io-500-webpage#4]
Hey @jeanbez ,

If I sort a list by say IOPS and then leave a Disqus comment on it, when someone views that list with a different sort criteria, will they see my comment?  It might be confusing if they can.  Perhaps we should have a separate Disqus comment section for each view.

**Comment by jeanbez** [comment]
@johnbent each page (view) has an unique identifier based on the URL do identify the Disqus comments. Thus, in that case, you will not be able to see comments if you sort in a different manner, as the URL will also change.

**Comment by johnbent** [comment]
You're the best!
