### ISSUE TITLE
IO500 logo

### ISSUE THREAD

**Issue by JulianKunkel** [VI4IO/io-500-webpage#7]
Use the current IO500 logo from 
https://www.vi4io.org/_media/io500/logo-io500.png?w=200&tok=4605e6

**Comment by johnbent** [comment]
Jean Luca, can you please address this?  Once we have the site live, we can always submit pull requests to change the logo if people have new logos they'd like to propose.

**Comment by jeanbez** [comment]
Done! I noticed that the color of the logo (red) is slightly stronger than the red used in the rest of the website. Should I change every other red to make consistent?

**Comment by johnbent** [comment]
Yeah, that seems like a great idea if it’s not too much trouble.

John Bent (he/him/his)
Seagate Managing Technologist
505.795.3167
john.bent@seagate.com
________________________________

**Comment by jeanbez** [comment]
Done!

**Comment by johnbent** [comment]
You’re the best!

John Bent (he/him/his)
Seagate Managing Technologist
505.795.3167
john.bent@seagate.com
________________________________
