### ISSUE TITLE
Enable link: Return to main page

### ISSUE THREAD

**Issue by JulianKunkel** [VI4IO/io-500-webpage#9]
Clicking on the IO500 logo might return to the main page. 
Do we really need a "home" button? We could have both.

**Comment by johnbent** [comment]
Jean Luca, can you please make the logo link to 'Home'?  Yeah, I think it's nicer to have both for some users who might not realize they can click on the logo.  If our nav bar ever gets overly crowded, 'Home' would be a nice possible victim but I don't think we need the real estate yet so seems cool to me to have both as Julian suggests.

**Comment by jeanbez** [comment]
This has been fixed while fixing #7 (commit c3294a9c36181f0f2cf80b1877de734a12400e7d).

**Comment by johnbent** [comment]
Closing as this was fixed.  Please re-open if problems reoccur.
